# Generated by Django 5.2.7 on 2026-02-24 19:09

import django.utils.timezone
import users.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.PositiveIntegerField(choices=[(0, 'ManagerAdministration'), (1, 'ManagerModification'), (2, 'EditManagerOnlyPermissions'), (3, 'EditAdminPermissions'), (4, 'UsersModification'), (5, 'UsersAdministration'), (6, 'BookBasesAdministration'), (7, 'BookBasesModification'), (8, 'LibraryBranchesAdministration'), (9, 'LibraryBranchesModification'), (10, 'BookMovementManagement'), (11, 'BookReservationManagement')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_permission',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=users.enums.Gender['Male'], max_length=10)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('client', 'Client')], default=users.enums.UserRole['Client'], max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='users', to='users.userpermission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
