# Generated by Django 5.2.7 on 2026-03-13 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('positions', '0001_initial'),
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='code',
            field=models.PositiveIntegerField(choices=[(0, 'ManagerAdministration'), (1, 'ManagerModification'), (2, 'EditManagerOnlyPermissions'), (3, 'EditAdminPermissions'), (4, 'UsersModification'), (5, 'UsersAdministration'), (6, 'BookBasesAdministration'), (7, 'BookBasesModification'), (8, 'LibraryBranchesAdministration'), (9, 'LibraryBranchesModification'), (10, 'BookMovementManagement'), (11, 'BookReservationManagement'), (12, 'PositionsModification'), (13, 'PositionsAdministration'), (14, 'StaffPositionsAdministration')]),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='library.librarybranch')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='positions.staffposition')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_profile',
                'ordering': ('created_at',),
            },
        ),
    ]
