# Generated by Django 5.2.7 on 2026-03-16 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_alter_librarybranch_id'),
        ('users', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='library_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='library.librarybranch'),
        ),
    ]
