# Generated by Django 5.2.7 on 2026-03-16 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_alter_librarybranch_id'),
        ('users', '0005_staff_profile_library_branch_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='library_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='library.librarybranch'),
        ),
    ]
