# Generated by Django 5.2.7 on 2026-03-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_staffprofile_library_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='code',
            field=models.PositiveIntegerField(choices=[(0, 'ManagerAdministration'), (1, 'ManagerModification'), (2, 'EditManagerOnlyPermissions'), (3, 'EditAdminPermissions'), (4, 'UsersModification'), (5, 'UsersAdministration'), (6, 'BookBasesAdministration'), (7, 'BookBasesModification'), (8, 'LibraryBranchesAdministration'), (9, 'LibraryBranchesModification'), (10, 'BookMovementManagement'), (11, 'BookReservationManagement'), (12, 'PositionsModification'), (13, 'PositionsAdministration'), (14, 'StaffPositionsAdministration'), (15, 'ManageSuppliers')]),
        ),
    ]
