# Generated by Django 5.2.7 on 2026-04-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userpermission_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
    ]
