# Generated by Django 5.2.7 on 2026-04-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='code',
            field=models.PositiveIntegerField(choices=[(0, 'ManagerAdministration'), (1, 'ManagerModification'), (2, 'EditManagerOnlyPermissions'), (3, 'EditAdminPermissions'), (4, 'UsersModification'), (5, 'UsersAdministration'), (6, 'BookBasesAdministration'), (7, 'BookBasesModification'), (8, 'LibraryBranchesAdministration'), (9, 'LibraryBranchesModification'), (10, 'BookMovementManagement'), (11, 'BookReservationManagement'), (12, 'PositionsModification'), (13, 'PositionsAdministration'), (14, 'StaffPositionsAdministration'), (15, 'ManageSuppliers'), (16, 'AmenitiesAdministration'), (17, 'AmenitiesModification')]),
        ),
    ]
