# Generated by Django 5.2.7 on 2026-05-03 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def forwards_profile_for_existing_clients(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    UserProfile = apps.get_model('users', 'UserProfile')
    for user in CustomUser.objects.filter(role='client').iterator():
        UserProfile.objects.get_or_create(user_id=user.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_deleted_at'),
        ('works', '0015_work_volume_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_works', models.ManyToManyField(blank=True, related_name='favorited_in_user_profiles', to='works.work')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'ordering': ('created_at',),
            },
        ),
        migrations.RunPython(forwards_profile_for_existing_clients, migrations.RunPython.noop),
    ]
