# Generated by Django 5.2.7 on 2026-05-03 10:32

from datetime import timedelta

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def copy_implicit_favorite_m2m_to_userfavorite(apps, schema_editor):
    UserFavorite = apps.get_model('users', 'UserFavorite')
    if UserFavorite.objects.exists():
        return
    base = timezone.now()
    with schema_editor.connection.cursor() as c:
        c.execute(
            'SELECT id, userprofile_id, work_id FROM user_profile_favorite_works ORDER BY id',
        )
        rows = c.fetchall()
    for row_pk, profile_id, work_id in rows:
        UserFavorite.objects.create(
            profile_id=profile_id,
            work_id=work_id,
            created_at=base + timedelta(milliseconds=row_pk),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_profile'),
        ('works', '0015_work_volume_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_links', to='users.userprofile')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_profile_links', to='works.work')),
            ],
            options={
                'db_table': 'user_profile_favorite_link',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RunPython(copy_implicit_favorite_m2m_to_userfavorite, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_works',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_works',
            field=models.ManyToManyField(blank=True, related_name='favorited_in_user_profiles', through='users.UserFavorite', to='works.work'),
        ),
        migrations.AddConstraint(
            model_name='userfavorite',
            constraint=models.UniqueConstraint(fields=('profile', 'work'), name='user_profile_favorite_link_profile_work_uniq'),
        ),
    ]
