# Generated by Django 5.2.7 on 2026-04-04 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0002_alter_librarybranch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amenity_name', models.CharField(max_length=50)),
                ('preview_link', models.CharField(blank=True)),
                ('vendor_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'amenity_vendor',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preview_link', models.CharField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amenities', to='library.librarybranch')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amenities', to='amenity.amenityvendor')),
            ],
            options={
                'db_table': 'amenity',
                'ordering': ('created_at',),
            },
        ),
    ]
