# Generated by Django 5.2.7 on 2026-04-05 10:48

import common_core.classes.view_set_base
import django.db.models.deletion
import rest_framework.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityVendorViewSet',
            fields=[
                ('amenityvendor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='amenity.amenityvendor')),
            ],
            bases=(common_core.classes.view_set_base.ViewSetBase, 'amenity.amenityvendor', rest_framework.mixins.ListModelMixin, rest_framework.mixins.RetrieveModelMixin, rest_framework.mixins.CreateModelMixin, rest_framework.mixins.UpdateModelMixin, rest_framework.mixins.DestroyModelMixin),
        ),
    ]
