# Generated by Django 5.2.7 on 2026-04-22 23:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0009_rename_book_models_to_work'),
        ('library', '0002_alter_librarybranch_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBasisFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='works.work')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'book_basis_feedback',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('work', 'client'), name='uniq_book_basis_feedback_per_client')],
            },
        ),
        migrations.CreateModel(
            name='LibraryBranchFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_branch_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('library_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='library.librarybranch')),
            ],
            options={
                'db_table': 'library_branch_feedback',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('library_branch', 'client'), name='uniq_library_branch_feedback_per_client')],
            },
        ),
    ]
