# Generated by Django 5.2.7 on 2026-06-12 20:42

import django.core.validators
import django.db.models.deletion
import uuid
import work_reservations.models.reservation.model_config
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0004_rename_librarybranch_preview_to_preview_link'),
        ('works', '0016_work_online_version_filefield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)])),
                ('status', models.PositiveIntegerField(choices=[(0, 'Open'), (1, 'Closed'), (2, 'ClientDeclined'), (3, 'StaffDeclined')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserved_till', models.DateField(validators=[work_reservations.models.reservation.model_config.reserved_till_validator])),
                ('closed_at', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_reservations_client', to=settings.AUTH_USER_MODEL)),
                ('library_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_reservations', to='library.librarybranch')),
                ('responsible_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_reservations_staff', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='works.work')),
            ],
            options={
                'db_table': 'work_reservation',
                'ordering': ('created_at', 'status', 'reserved_till'),
            },
        ),
    ]
