# Generated by Django 5.2.7 on 2026-04-09 06:27

import book_loan.enums
import common_core.date_utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books_model', '0004_alter_bookbasis_id_alter_genre_id'),
        ('library', '0002_alter_librarybranch_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_phone', models.CharField(max_length=30)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_fullname', models.CharField(max_length=50)),
                ('loaned_till', models.DateField(default=common_core.date_utils.get_future_from_today_date)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=book_loan.enums.BookLoanStatus['Open'])),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='books_model.book')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_loans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_book_loans', to=settings.AUTH_USER_MODEL)),
                ('library_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_loans', to='library.librarybranch')),
            ],
            options={
                'db_table': 'book_loan',
                'ordering': ('updated_at', 'created_at', 'closed_at'),
            },
        ),
    ]
