# Generated by Django 5.2.7 on 2025-11-16 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'genre',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='BookBasis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('created_year', models.PositiveIntegerField()),
                ('online_version_link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_bases_ids', to='books_model.genre')),
            ],
            options={
                'db_table': 'book_basis',
                'ordering': ('created_at',),
            },
        ),
    ]
