# Generated by Django 5.2.7 on 2025-11-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookbasis',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
