# Generated by Django 5.2.7 on 2026-01-25 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_model', '0002_rename_genre_id_bookbasis_genre'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('totalCount', models.PositiveIntegerField()),
                ('availableCount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_basis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books_model.bookbasis')),
                ('library_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='library.librarybranch')),
            ],
            options={
                'db_table': 'book',
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('book_basis', 'library_branch'), name='unique_book_basis_per_library_branch')],
            },
        ),
    ]
