# Generated by Django 5.2.7 on 2026-02-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_model', '0003_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('library_branch', 'book_basis', 'id')},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='availableCount',
            new_name='available_count',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='totalCount',
            new_name='total_count',
        ),
    ]
