# Generated by Django 5.2.7 on 2026-03-17 20:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0009_rename_book_models_to_work'),
        ('library', '0002_alter_librarybranch_id'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='works.work')),
                ('library_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_branch', to='library.librarybranch')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'inventory_movements',
                'ordering': ('created_at',),
            },
        ),
    ]
