# Generated by Django 5.2.7 on 2026-04-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_alter_book_id_alter_bookbasis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookbasis',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]

