# Generated by Django 5.2.7 on 2026-04-05 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_fix_bookbasis_autofield_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookbasis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]

