# Generated by Django 5.2.7 — замена CharField `author` на ForeignKey; данные переносятся из строки

import uuid

import django.db.models.deletion
from django.db import migrations, models


def forwards_migrate_authors(apps, schema_editor):
    BookBasis = apps.get_model('works', 'BookBasis')
    Author = apps.get_model('authors', 'Author')
    for bb in BookBasis.objects.all():
        legacy: str = bb.author_legacy
        author, _ = Author.objects.get_or_create(
            name=legacy,
            defaults={'id': uuid.uuid4()},
        )
        bb.author_id = author.id
        bb.save(update_fields=['author_id'])


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('authors', '0001_initial'),
        ('works', '0004_alter_bookbasis_id_alter_genre_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookbasis',
            old_name='author',
            new_name='author_legacy',
        ),
        migrations.AddField(
            model_name='bookbasis',
            name='author',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='book_bases',
                to='authors.author',
            ),
        ),
        migrations.RunPython(forwards_migrate_authors, backwards_noop),
        migrations.RemoveField(
            model_name='bookbasis',
            name='author_legacy',
        ),
        migrations.AlterField(
            model_name='bookbasis',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='book_bases',
                to='authors.author',
            ),
        ),
    ]

