# Generated by Django 5.2.7 on 2026-04-29 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('library', '0004_rename_librarybranch_preview_to_preview_link'),
        ('works', '0013_work_category_str_enum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitem',
            options={'ordering': ('library_branch', 'work', 'id')},
        ),
        migrations.AlterField(
            model_name='work',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='works', to='authors.author'),
        ),
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(choices=[('book', 'Book'), ('scientific_article', 'ScientificArticle'), ('collected_articles', 'CollectedArticles'), ('journal', 'Journal'), ('comic', 'Comic'), ('lecture_notes', 'LectureNotes')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='library_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='library.librarybranch'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='works.work'),
        ),
    ]
