# Generated by Django 5.2.7 on 2026-05-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0014_align_after_category_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='volume',
            field=models.PositiveIntegerField(default=1, verbose_name='Объём (страниц)'),
        ),
    ]
